"""Shared helpers the case modules build on: correlation, polling, audit control.

Correlation note. The runtime returns `X-Prism-Ingress-Request-Id`, but that is
a transport correlation value generated by middleware and is NOT the
`ingress_request_id` persisted in request_logs — a caller cannot use it to find
its own row. The suite therefore correlates with an id watermark taken
immediately before each request, which is exact as long as the suite is the
only traffic source against this instance.
"""

from __future__ import annotations

import time
import uuid
from datetime import datetime, timedelta, timezone

from .runner import CaseContext
from .store import StoreUnavailable

# The telemetry outbox is drained by a background worker, so a row is not
# visible the instant the caller's response returns.
TELEMETRY_TIMEOUT_S = 45.0
POLL_INTERVAL_S = 0.25


def marker(prefix: str) -> str:
    """A per-case nonce that shows up verbatim in captured bodies."""
    return f"{prefix}_{uuid.uuid4().hex[:12].upper()}"


def _window_bounds() -> tuple[str, str]:
    now = datetime.now(timezone.utc)
    return (
        (now - timedelta(hours=6)).strftime("%Y-%m-%dT%H:%M:%SZ"),
        (now + timedelta(hours=1)).strftime("%Y-%m-%dT%H:%M:%SZ"),
    )


def audit_window() -> dict[str, str]:
    """The audit list's required window keys."""
    start, end = _window_bounds()
    return {"from": start, "to": end}


def export_window() -> dict[str, str]:
    """The requests export's required range keys, which differ from the audit list's."""
    start, end = _window_bounds()
    return {"from_time": start, "to_time": end}


def wait_for_rows(
    context: CaseContext,
    table: str,
    after_id: int,
    *,
    expected: int = 1,
    timeout_s: float = TELEMETRY_TIMEOUT_S,
) -> list[dict]:
    """Poll until at least `expected` new rows exist, then return them.

    Raises StoreUnavailable if the database becomes unreachable while waiting,
    so a read failure can never be reported as "nothing was written".
    """
    deadline = time.monotonic() + timeout_s
    rows: list[dict] = []
    while time.monotonic() < deadline:
        rows = context.store.json_rows(f"select * from {table} where id > {int(after_id)} order by id")
        if len(rows) >= expected:
            return rows
        time.sleep(POLL_INTERVAL_S)
    return rows


def assert_no_new_rows(context: CaseContext, watermarks: dict[str, int], *, settle_s: float = 3.0) -> dict[str, int]:
    """Give the async writers time to prove they wrote nothing, then confirm."""
    time.sleep(settle_s)
    counts = context.store.counts_since(watermarks)
    for table, count in counts.items():
        context.expect_eq(f"no new rows in {table}", 0, count)
    return counts


def set_audit_mode(context: CaseContext, *, openai_mode: str) -> dict:
    """Set the openai audit policy and return the settings the server echoed back."""
    current = context.gateway.management("GET", "/settings/audit")
    if current.status != 200:
        raise StoreUnavailable(f"could not read audit settings: HTTP {current.status} {current.text[:200]}")
    revision = (current.json() or {}).get("revision")
    payload = {
        "operation_id": str(uuid.uuid4()),
        "expected_revision": revision,
        "policies": [
            {"family": "openai", "mode": openai_mode},
            {"family": "anthropic", "mode": "disabled"},
            {"family": "gemini", "mode": "disabled"},
        ],
    }
    applied = context.gateway.management("PUT", "/settings/audit", body=payload)
    if applied.status != 200:
        raise StoreUnavailable(f"audit PUT failed: HTTP {applied.status} {applied.text[:300]}")
    return (applied.json() or {}).get("settings", {})


def audit_mode(context: CaseContext) -> str | None:
    response = context.gateway.management("GET", "/settings/audit")
    if response.status != 200:
        return None
    for policy in (response.json() or {}).get("policies", []):
        if policy.get("family") == "openai":
            return policy.get("mode")
    return None


def live_model(context: CaseContext) -> str:
    """The caller-visible model backed by a working upstream credential."""
    model = context.state.get("live_model")
    if not model:
        context.block("no live upstream model configured (set PRISM_CHAIN_LIVE_MODEL and PRISM_CHAIN_UPSTREAM_API_KEY)")
    return model


def dead_model(context: CaseContext) -> str:
    """A caller-visible model whose upstream credential is known not to work.

    Used for the honest failure path. Discovered at bootstrap rather than
    hard-coded, so the suite keeps working when the configuration changes.
    """
    model = context.state.get("dead_model")
    if not model:
        context.block("no model with a rejecting upstream was discovered")
    return model


def assemble_stream_content(sse_events: list[str]) -> str:
    """Concatenate the assistant text out of an OpenAI-style SSE stream.

    The upstream splits an answer across arbitrary delta boundaries, so the
    marker only reappears once the deltas are joined in order.
    """
    import json

    assembled = ""
    for frame in sse_events:
        for line in frame.splitlines():
            line = line.strip()
            if not line.startswith("data:"):
                continue
            payload = line[len("data:") :].strip()
            if not payload or payload == "[DONE]":
                continue
            try:
                event = json.loads(payload)
            except ValueError:
                continue
            for choice in event.get("choices") or []:
                delta = choice.get("delta") or {}
                assembled += delta.get("content") or ""
    return assembled


def as_int(value: object) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def as_bool(value: object) -> bool | None:
    if isinstance(value, bool):
        return value
    if value in ("t", "true", "True", 1, "1"):
        return True
    if value in ("f", "false", "False", 0, "0"):
        return False
    return None
