ALTER TABLE public.model_access_targets
    DROP CONSTRAINT IF EXISTS chk_model_access_targets_target_metadata;

ALTER TABLE public.model_access_targets
    DROP COLUMN IF EXISTS weight,
    DROP COLUMN IF EXISTS target_priority;

CREATE TABLE IF NOT EXISTS public.profile_api_family_audit_settings (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id integer NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    api_family character varying(50) NOT NULL,
    audit_enabled boolean NOT NULL,
    audit_capture_bodies boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT chk_profile_api_family_audit_settings_api_family CHECK (api_family IN ('openai', 'anthropic', 'gemini')),
    CONSTRAINT chk_profile_api_family_audit_settings_capture_requires_enabled CHECK (audit_enabled OR NOT audit_capture_bodies),
    CONSTRAINT uq_profile_api_family_audit_settings_profile_family UNIQUE (profile_id, api_family)
);

CREATE INDEX IF NOT EXISTS idx_profile_api_family_audit_settings_profile_id
    ON public.profile_api_family_audit_settings (profile_id);
